# main menu navigation
menu:
  home_title: /
  archive_title: /archive
  about_title: /about

duoshuo_shortname: hunnble
busuanzi: true

# links to other websites
links:
  github:
    href: https://github.com/hunnble
    icon: /images/github.png
    color: black
  weibo:
    href: http://www.weibo.com/5597091497/profile?topnav=1&wvr=6
    icon: /images/weibo.png
    color: red
  zhihu:
    href: https://www.zhihu.com/people/han-te-79
    icon: /images/zhihu.png
    color: blue
  mail:
    href: mailto:hante_hunter@163.com
    icon: /images/mail.png
    color: green
  # douban:
  #   href: https://book.douban.com/
  #   icon: /images/douban.png
  #   color: green
  # twitter:
  #   href: https://twitter.com/
  #   icon: /images/twitter.png
  #   color: blue
  # facebook:
  #   href: https://www.facebook.com
  #   icon: /images/facebook.png
  #   color: indigo lighten-1
  # google:
  #   href: http://www.google.com
  #   icon: /images/google.png
  #   color: green
  # stackoverflow:
  #   href: https://stackoverflow.com/
  #   icon: /images/stackoverflow.png
  #   color: orange lighten-3

# rss
rss: /atom.xml

# friends
# friends: false
friends:
  hunnble: http://www.hunnble.com

#widgits
widgits:
  profile: true
  search: true
  archive: true
  category: true
  tag: true
  recent_posts: true
  recent_comments: true
  links: true

# Miscelaneous
favicon: /images/favicon.ico

# images
images:
  home: /images/background.jpg
  about: /images/background.jpg
  archive: /images/archive.jpg
  category: /images/archive.jpg
  tag: /images/archive.jpg

# avatar
avatar: /images/avatar.png

# fonts loaded in the <head>
fonts:
- /fonts/material-icons/2fcrYFNaTjcS6g4U3t-Y5UEw0lE80llgEseQY3FEmqw.woff2

# stylesheets loaded in the <head>
stylesheets:
- /css/materialize.min.css
- /css/main.css

# scripts loaded in the end of the body
scripts:
- /js/main.js

# highlight code block, make sure that _config.yml in root dir be false
highlight:
  enable: true
  style: default

# use fancybox to show pictures
fancybox: true

# pagination numbers
prev_num: 4
next_num: 4

# count of recent posts
recent_count: 5

# Date / Time format
date_format: YYYY MMM Do
time_format: Ah:m:ss

# translucent
translucent: false

# blur style for background, can be set in 1, 2, 3 or false
background_blur: false

# color and subColor
color: lighten-3 teal
subColor: blue-grey
titleColor: white
contentColor: black

# tag colors
tagColors:
  - amber
  - green
  - red
  - yellow
  - blue

# shadow level
shadowLevel: 5

# mode
# layout: parallax/default
mode:
  layout: parallax
  # column: default

parallax_height: 400
